
spring:

  webflux:
    cors:
      allow-credentials: true
      allowed-origins: "http://localhost:3000, https://outro-site.com"

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: "confeitech"
  datasource:

    ## Configuração para SQLServer:
#    url: jdbc:sqlserver://confeitech-server.database.windows.net:1433;databaseName=confeitech-bd;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    username: confeitechADM
#    password: Confeitech@
#    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

    ## Configuração para MySQL Local:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/confeitech}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:

        ## Dialeto MYSQL
        dialect: org.hibernate.dialect.MySQLDialect

        ## Dialeto SQLServer
#        dialect: org.hibernate.dialect.SQLServerDialect



#
#  flyway:
#    enabled: false
#    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}

server:
  port: 8080
  shutdown: graceful

  logging:
    level:
      org:
        springframework:
          security=DEBUG:

