
spring:
  application:
    name: "confeitech"
  datasource:
    url: ${DATASOURCE_URL:jdbc:mysql://localhost:3306/confeitech}
    username: ${DATASOURCE_USERNAME:root}
    password: ${DATASOURCE_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  flyway:
    enabled: false
    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}

server:
  port: 8080
  shutdown: graceful