
spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  application:
    name: "confeitech"
  datasource:
    url: jdbc:sqlserver://confeitech-server.database.windows.net:1433;databaseName=confeitech-bd;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: confeitechADM
    password: Confeitech@
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: ${DATASOURCE_URL:jdbc:sqlserver://confeitech-server}
#    username: ${DATASOURCE_USERNAME:confeitechADM}
#    password: ${DATASOURCE_PASSWORD:Confeitech@}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
#
#  flyway:
#    enabled: false
#    locations: ${FLYWAY_LOCATIONS:classpath:db/migration}

server:
  port: 8080
  shutdown: graceful